#-------------------------------------------------------------------------------
# Set environment variables
#-------------------------------------------------------------------------------
export PATH="$PATH:~/bin"
export VISUAL=vi
export EDITOR=$VISUAL
#-------------------------------------------------------------------------------
# Configure history
#-------------------------------------------------------------------------------
export HISTTIMEFORMAT="[%Y-%m-%d %T] :: "
export HISTCONTROL=ignoreboth
#-------------------------------------------------------------------------------
# Make sure no PROMPT_COMMAND is set since that ruins my GNU Screen window title
#-------------------------------------------------------------------------------
export PROMPT_COMMAND=
#-------------------------------------------------------------------------------
# Aliasses
#-------------------------------------------------------------------------------
alias ls='ls -h --color'
alias ll='ls -alF'
alias la='ls -l'
alias docker='sudo docker'
alias pre-commit='uv tool run pre-commit'
alias update='sudo /opt/update-dc/000-update-dev-dc.sh'
#-------------------------------------------------------------------------------
# Run any local .bashrc files
#-------------------------------------------------------------------------------
if [ -f ~/.bashrc.local ]; then
    source ~/.bashrc.local
fi
#-------------------------------------------------------------------------------
# Git repository greeter
#-------------------------------------------------------------------------------
last_repository=
check_directory_for_new_repository() {
	current_repository=$(git rev-parse --show-toplevel 2> /dev/null)

	if [ "$current_repository" ] && \
	  [ "$current_repository" != "$last_repository" ]; then
		onefetch
	fi
	last_repository=$current_repository
}
cd() {
	builtin cd "$@"
	check_directory_for_new_repository
}
check_directory_for_new_repository
#-------------------------------------------------------------------------------
# Update reminder
#-------------------------------------------------------------------------------
if [ -f /var/log/dev-dc-last-update ]; then
    _last_update=$(stat -c %Y /var/log/dev-dc-last-update)
    _now=$(date +%s)
    _days_since=$(( (_now - _last_update) / 86400 ))
    if [ "$_days_since" -gt 5 ]; then
        echo "It has been $_days_since days since the last update. Run 'update' to update the container."
    fi
    unset _last_update _now _days_since
fi
#-------------------------------------------------------------------------------
# Start Starship for the prompt
#-------------------------------------------------------------------------------
eval "$(starship init bash)"
#-------------------------------------------------------------------------------
# Done!
#-------------------------------------------------------------------------------
