#-------------------------------------------------------------------------------
# Set environment variables
#-------------------------------------------------------------------------------
export PATH="$PATH:~/bin"
export VISUAL=vi
export EDITOR=$VISUAL
#-------------------------------------------------------------------------------
# Configure history
#-------------------------------------------------------------------------------
export HISTTIMEFORMAT="[%Y-%m-%d %T] :: "
export HISTCONTROL=ignoreboth
#-------------------------------------------------------------------------------
# Make sure no PROMPT_COMMAND is set since that ruins my GNU Screen window title
#-------------------------------------------------------------------------------
export PROMPT_COMMAND=
#-------------------------------------------------------------------------------
# Aliasses
#-------------------------------------------------------------------------------
alias ls='ls -h --color'
alias ll='ls -alF'
alias la='ls -l'
alias docker='sudo docker'
alias pre-commit='uvx pre-commit'
#-------------------------------------------------------------------------------
# Run any local .bashrc files
#-------------------------------------------------------------------------------
if [ -f ~/.bashrc.local ]; then
    source ~/.bashrc.local
fi
#-------------------------------------------------------------------------------
# Git repository greeter
#-------------------------------------------------------------------------------
last_repository=
check_directory_for_new_repository() {
	current_repository=$(git rev-parse --show-toplevel 2> /dev/null)

	if [ "$current_repository" ] && \
	  [ "$current_repository" != "$last_repository" ]; then
		onefetch
	fi
	last_repository=$current_repository
}
cd() {
	builtin cd "$@"
	check_directory_for_new_repository
}
check_directory_for_new_repository
#-------------------------------------------------------------------------------
# Start Starship for the prompt
#-------------------------------------------------------------------------------
eval "$(starship init bash)"
#-------------------------------------------------------------------------------
# Done!
#-------------------------------------------------------------------------------
